Add basic views
toggle-corp/base-react-app pull request #5
Opened 2021-07-23 08:13 UTC by AdityaKhatri

2021-07-23 08:47 UTC, tnagorra requested changes

2021-07-23 08:47 UTC, tnagorra commented on app/Base/public-components/Navbar/index.tsx
> +                        You don&apos;t have any notification
I don't know which one is better but
```suggestion
                        {'You don\'t have any notification'}
```

2021-07-23 08:47 UTC, tnagorra commented on app/Base/public-components/PageContent/index.tsx
> +import React from 'react';
Let's move this the root components folder

2021-07-26 03:58 UTC, frozenhelium commented on app/Base/public-components/Navbar/index.tsx
> +                        You don&apos;t have any notification
Both are fine

2021-07-26 07:10 UTC, tnagorra approved these changes

2021-07-26 12:51 UTC, merged